### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by pwfraley** [rodrigolive/mongoose#30]
Hi,

I have a fairly simple model with just a dozen fields in it, inlcuding one array field and no relations.  Now fetching a query from the database which returns 533 objects, it takes about 13 seconds.  Now that seems really slow ...  I then tried fetching without the ->all() then it takes about 2 seconds, but itterating over the items and pulling out the data I need takes about 11 more seconds.

I let it run with NYTProf and it seems most time is spent in validation.

I can provide you with the nytprof outputfile if you need.

Is this a known issue (I could not find anything about this).

Also when I fetch the data directly using the Mongo perl driver I can get thru the query in about 2 seconds.

**Comment by diegok** [comment]
Hello @pwfraley 

it's true that mongoose make it slower, but it's the cost to pay for wrapping everything into objects. I'll close this issue but I'll be more than happy to have pull-requests to make Mongoose faster.
