### ISSUE TITLE
documentation bug: raw trait no longer needed on DateTime attributes

### ISSUE THREAD

**Issue by gmorten1** [rodrigolive/mongoose#31]
the pod indicates that you need to specify the raw trait if you want to bypass the Mongoose serialization of DateTime and instead use the more storage-efficient MongoDB mechanism. from looking at my data and then reading the changelog, i believe this hasn't been true since version .08

**Comment by diegok** [comment]
@gmorten1 a bit late, but already fixed. It will hit cpan soon.
