### ISSUE TITLE
Integers being stored as strings

### ISSUE THREAD

**Issue by tophopstop** [rodrigolive/mongoose#32]
I've got a Mongoose object with an attribute that's defined to be an Int.   If set the attribute with a quoted string (either single or double) and save the object, what actually makes it into MongoDB is a string (which is problematic for querying further down the line) rather than Int as intended.

Here's a sample Mongoose object:
```perl
package MongooseTest;
use strict;
use warnings;
use Mongoose::Class;
with 'Mongoose::Document';
has_one 'sampleInt' => ( isa => 'Int' );
1;
```
and test that shows the problematic behavior:
```perl
use strict;
use warnings;
use Test::More;    
use MongooseTestDB;

my $testdb = MongooseTestDB->new()->init;

use MongooseTest;
MongooseTest->collection->drop; # clean slate for testing

my $testString = '1234';
my $c = MongooseTest->new( sampleInt => $testString );
$c->save;

# try to match as a string
my $r = MongooseTest->collection->find( {sampleInt=> '1234'} );
is($r->count,1,q|found by string.|);

# try to match as an int.
$r = MongooseTest->collection->find( {sampleInt=> 1234} );
is($r->count,1,q|found by int.|);

done_testing;
```
I understand that **Mongoose** rides on top of the **MongoDB** module, which says [its up to you to cast data to proper types yourself](https://metacpan.org/pod/MongoDB::DataTypes#Dealing-with-numbers-and-strings-in-Perl) if you care about how they end up in MongoDB.  But with the meta layer provided by **Moose**, it seems that **Mongoose** can/should take care of the cast automatically.

**Comment by diegok** [comment]
I'm looking into this, and it seems reasonable what you suggest, the problem is it's only fixing half of the problem, the saving part but not the querying...

MongoDB driver has "fixed" this same part forcing everything that looks_like_number to be a number: https://metacpan.org/pod/MongoDB::BSON#looks_like_number 

So, I guess I can try to do it only when ```isa``` number type.
