### ISSUE TITLE
Invalid $VERSION declaration in Document.pm

### ISSUE THREAD

**Issue by miyagawa** [rodrigolive/mongoose#36]
Probably a misconfiguration of dzil, but the generated Document.pm has an invalid version declaration in $DB:: package: https://metacpan.org/source/RODRIGO/Mongoose-0.25/lib/Mongoose/Document.pm#L34

and that confuses modules like Module::Metadata that tries to evaluate VERSION by scanning the code.

**Comment by diegok** [comment]
It's solved in current (0.27) version and I hope on future releases. Can this issue be closed or it's needed to remove 0.25 from cpan?

**Comment by miyagawa** [comment]
No need to delete 0.25. Thanks!
