### ISSUE TITLE
Declaring non primary unique indexes (maybe with traits)

### ISSUE THREAD

**Issue by gentili** [rodrigolive/mongoose#4]
I really like specifying everything about my collections in the Moose object definitions and mongoose seems to cover most of what I'm looking for (and thank you :).  It looks like if I want non primary unique indexes or compound indexes I have to create those separately.  Mongoose could maybe take care of that for you through traits. Do you have any plans to add such functionality?

**Comment by diegok** [comment]
As noted by @rodrigolive (5 years ago) this is a one time OP. You can easily implement this role if you want and I wold love to evaluate into making it part of mongoose, but I suspect this is not the case 5 years after this issue was created :-/
