### ISSUE TITLE
Update to MongoDB v2 Driver

### ISSUE THREAD

**Issue by diegok** [rodrigolive/mongoose#51]
There is a new version of MongoDB Driver that makes almost all tests to fail as it has moved to `BSON::*` on some internal objects and moved away from `DateTime` to BSON::Time.

There are lots of other warnings and deprecations to be re-worked like `count()`.

**Comment by wreis** [comment]
https://metacpan.org/pod/MongoDB::Upgrading

**Comment by diegok** [comment]
Hey @wreis !. I've done it on this branch:

https://github.com/rodrigolive/mongoose/tree/mongodb-driver-v2

IIRC it's passing all tests on my box but failing some on some perl versions on travis-ci. I wanted to make sure my company tests are also passing as we're doing some nasty things whith this lib before pushing it to CPAN and never got the time to do it. Can you please install this branch and let me know if it works for you?. In that case I will happily push it forward.

Also, are you using this lib for some time or it's your first try?

**Comment by wreis** [comment]
hey @diegok, yeah, seen the branch. I am just adding a note to that docs as reference. I am not really using this module, but just actually helping on MongoDB's reverse deps list getting up to dated.

**Comment by wreis** [comment]
When trying to install this with perl-5.20.2, I am getting the following error:

The method 'batch' was not found in the inheritance hierarchy for Mongoose::Cursor at /home/vagrant/local/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Expor
ter.pm line 419                                                                                                                                                                                       Moose::around('batch', 'CODE(0x4e6ca28)') called at /home/vagrant/.cpanm/work/1538682744.10121/mongoose-mongodb-driver-v2/lib/Mongoose/Cursor.pm line 19
        require Mongoose/Cursor.pm at /home/vagrant/.cpanm/work/1538682744.10121/mongoose-mongodb-driver-v2/lib/Mongoose/Engine.pm line 10                                                            Mongoose::Engine::BEGIN at /home/vagrant/.cpanm/work/1538682744.10121/mongoose-mongodb-driver-v2/lib/Mongoose/Cursor.pm line 0                                                        
        eval {...} at /home/vagrant/.cpanm/work/1538682744.10121/mongoose-mongodb-driver-v2/lib/Mongoose/Cursor.pm line 0                                                                             require Mongoose/Engine.pm at /home/vagrant/local/lib/perl5/Module/Runtime.pm line 314                                                                                                
        Module::Runtime::require_module('Mongoose::Engine') called at /home/vagrant/local/lib/perl5/Module/Runtime.pm line 391                                                                        eval {...} at /home/vagrant/local/lib/perl5/Module/Runtime.pm line 391                                                                               
        Module::Runtime::use_package_optimistically('Mongoose::Engine') called at /home/vagrant/local/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Util.pm line 348                          
        Moose::Util::_load_user_class('Mongoose::Engine', undef) called at /home/vagrant/local/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Util.pm line 146                                         Moose::Util::_apply_all_roles('MooseX::Role::Parameterized::Meta::Role::Parameterized=HASH(0x4e49f68)', undef, 'Mongoose::Engine') called at /home/vagrant/local/lib/perl5/x86_64-linu
x-gnu-thread-multi/Moose/Util.pm line 113                                                                                                                                                             Moose::Util::apply_all_roles('MooseX::Role::Parameterized::Meta::Role::Parameterized=HASH(0x4e49f68)', 'Mongoose::Engine') called at /home/vagrant/local/lib/perl5/x86_64-linux-gnu-th
read-multi/Moose/Role.pm line 25                                                                                                                                                                      Moose::Role::with('MooseX::Role::Parameterized::Meta::Role::Parameterized=HASH(0x4e49f68)', 'Mongoose::Engine') called at /home/vagrant/local/lib/perl5/MooseX/Role/Parameterized.pm l
ine 80                                                                                                                                                                                                MooseX::Role::Parameterized::with('MooseX::Role::Parameterized::Meta::Role::Parameterized=HASH(0x4e49f68)', 'Mongoose::Engine') called at /home/vagrant/local/lib/perl5/x86_64-linux-g
nu-thread-multi/Moose/Exporter.pm line 419                                                                                                                                                            MooseX::Role::Parameterized::with('Mongoose::Engine') called at /home/vagrant/.cpanm/work/1538682744.10121/mongoose-mongodb-driver-v2/lib/Mongoose/Document.pm line 51                
        Mongoose::Document::__ANON__('Moose::Meta::Class::__ANON__::SERIAL::11=HASH(0x4e2ea78)', 'operating_on', 'MooseX::Role::Parameterized::Meta::Role::Parameterized=HASH(0x4e49f68)', 'consumer', 'Moose::Meta::Class=HASH(0x4c8fc88)') called at /home/vagrant/local/lib/perl5/MooseX/Role/Parameterized/Meta/Trait/Parameterizable.pm line 85                                        
        MooseX::Role::Parameterized::Meta::Trait::Parameterizable::generate_role('Moose::Meta::Class::__ANON__::SERIAL::10=HASH(0x4e1ec80)', 'consumer', 'Moose::Meta::Class=HASH(0x4c8fc88)',
 'parameters', 'HASH(0x4dbf980)', 'orig_apply', 'CODE(0x26767f0)') called at /home/vagrant/local/lib/perl5/MooseX/Role/Parameterized/Meta/Trait/Parameterizable.pm line 110                   
        Class::MOP::Class:::around('CODE(0x26767f0)', 'Moose::Meta::Class::__ANON__::SERIAL::10=HASH(0x4e1ec80)', 'Moose::Meta::Class=HASH(0x4c8fc88)') called at /home/vagrant/local/lib/perl
5/x86_64-linux-gnu-thread-multi/Class/MOP/Method/Wrapped.pm line 164                                                                                                                          
        Moose::Meta::Class::__ANON__::SERIAL::10::_wrapped_apply('Moose::Meta::Class::__ANON__::SERIAL::10=HASH(0x4e1ec80)', 'Moose::Meta::Class=HASH(0x4c8fc88)') called at /home/vagrant/loc
al/lib/perl5/x86_64-linux-gnu-thread-multi/Class/MOP/Method/Wrapped.pm line 95                                                                                                                
        Moose::Meta::Class::__ANON__::SERIAL::10::apply('Moose::Meta::Class::__ANON__::SERIAL::10=HASH(0x4e1ec80)', 'Moose::Meta::Class=HASH(0x4c8fc88)') called at /home/vagrant/local/lib/pe
rl5/x86_64-linux-gnu-thread-multi/Moose/Util.pm line 171                                                                                                                                      
        Moose::Util::_apply_all_roles('Moose::Meta::Class=HASH(0x4c8fc88)', undef, 'Mongoose::Document') called at /home/vagrant/local/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Util.pm l
ine 113
        Moose::Util::apply_all_roles('Moose::Meta::Class=HASH(0x4c8fc88)', 'Mongoose::Document') called at /home/vagrant/local/lib/perl5/x86_64-linux-gnu-thread-multi/Moose.pm line 57
        Moose::with('Moose::Meta::Class=HASH(0x4c8fc88)', 'Mongoose::Document') called at /home/vagrant/local/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Exporter.pm line 419
        Moose::with('Mongoose::Document') called at t/after-save.t line 14
Compilation failed in require at /home/vagrant/.cpanm/work/1538682744.10121/mongoose-mongodb-driver-v2/lib/Mongoose/Engine.pm line 10.
BEGIN failed--compilation aborted at /home/vagrant/.cpanm/work/1538682744.10121/mongoose-mongodb-driver-v2/lib/Mongoose/Engine.pm line 10.
Compilation failed in require at /home/vagrant/local/lib/perl5/Module/Runtime.pm line 314.

**Comment by diegok** [comment]
Is is already merged into master and will be released to CPAN as v2.0.0 of mongoose to make it clear it uses driver v2.
