### ISSUE TITLE
Undeclared dependency on DateTime

### ISSUE THREAD

**Issue by andk** [rodrigolive/mongoose#55]
As per subject. Grep shows no declaration of a dependency for DateTime: https://grep.metacpan.org/search?q=DateTime&qd=Mongoose

Sample fail report for a missing DateTime: http://www.cpantesters.org/cpan/report/99081272

**Comment by diegok** [comment]
Ouch. Sure, this happened when I've migrated to MongoDB 2.x that is not requiring that anymore. Thank you.
